[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options = "deny"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy-Report-Only = "style-src 'self'; default-src 'self'; img-src 'self'; form-action 'none'; frame-ancestors 'none'; report-uri https://permissionsreview.report-uri.com/r/d/csp/wizard"
