[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Frame-Options = "deny"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; style-src 'self'; img-src 'self' https://koenrh.matomo.cloud; script-src 'sha256-cw201C1grsNRpAH1Ih4c76Vn4QKwCDHjyHE973JHzVg=' https://cdn.matomo.cloud; frame-ancestors 'none'; form-action 'none'; report-uri https://permissionsreview.report-uri.com/r/d/csp/enforce;"

[[headers]]
  for = "/images/*"
  [headers.values]
    Cache-Control = "public, max-age=604800"

[[headers]]
  for = "/css/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
